### ISSUE TITLE
Two problems while inviting new users

### ISSUE THREAD

**Issue by centigrade-thomas-becker** [wekan/wekan#1300]
## Issue
**Impacted version**: 0.46.0

The issue is related to #993. Since the original issue is closed and the changelog from 0.46 to 0.50 does not mention this problem I submitted a new issue.

When inviting **new users** to Wekan they receive the following mail:

```
Dear user,

admin invites you to Wekan for collaborations.

Please follow the link below:
https://example.com/sign-in

And your invitation code is: 148727

Thanks.
```

There is two problems with this:

- Since the person I just invited does not yet have an account on Wekan the link in the mail should point to "sign-up" and not "sign-in".
- When opened directly the page "sign-up" does not show a field for the invitation code. If you switch back and forth between sign-up and sign-in with the text links at the bottom then the field "Invitation Code" appears eventually. If you reload the page "sign-up" it is gone again.

Given these two problems I recon that the chances that a users successfully completes the invitation process are very slim.

**Comment by xet7** [comment]
@centigrade-thomas-becker 

Please try latest versio 0.50 first.

**Comment by xet7** [comment]
I think I fixed something related to this sometime.

**Comment by milesibastos** [comment]
Needed to be reopened because the problem still persist.
like commented by @GitHubJung on https://github.com/wekan/wekan/commit/c5540ddcbd27b2d1c1519dc98f21b68f1617b241
