### ISSUE TITLE
"Board not found" for a newly created board

### ISSUE THREAD

**Issue by teras** [wekan/wekan#1548]
## Issue

I have installed sandstorm.io and then wekan.
On top of this I created a wekan grain and I used it, me and some collegues.
The next day when I tried to open it again, this error welcomes me:
"Board not found"

I haven't imported it from trello, or haven't done anything in between that might have affected it.

**Impacted version**: 
0.63.0~2017-12-20

**Server Setup Information**:

* Operating System: Debian 9
* Deployment Method(snap/sandstorm/mongodb bundle): Sandstorm
* Http frontend (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): Apache passthrough with https certifcates
* Node Version: as per sandsrotm install script
* MongoDB Version: as per sandsrotm install script
* ROOT_URL environment variable http(s)://(subdomain).example.com(/suburl): https://dune.yot.is

**Problem description**:
Wekan grain doesn't start.
I have changed the name of the grain, I don't know if this is an issue.

I am able to create a nrew wekan grain, but the new one cannot rename it.

**Comment by xet7** [comment]
0.63 has a lot of bugs I think, compared to newest experimental version.

With newest experimental version old grains have opened correctly for me, if I don't import anything.

There will not be fixes to v0.63, so I'm closing this issue.

**Comment by xet7** [comment]
@teras 

It's already possible to install experimental version of Wekan from Sandstorm experimental app market, there is link at releases page:
https://github.com/wekan/wekan/releases

There is no integration needed, it's already at Sandstorm. Just couple of bugs to fix.

**Comment by ocdtrekkie** [comment]
I can go ahead and approve 0.78 if you like, @xet7.

I am still curious about this issue because it doesn't sound like an issue I think 0.63 has. Is it possible to download a backup of this Sandstorm grain and send it to one of us?

**Comment by ocdtrekkie** [comment]
Done, though, as I said, I am not sure it will fix the issue the OP is having. @teras, update the app, try it again, let us know.

**Comment by ma4git** [comment]
I just installed sandstorm and am testing Wekan. Having the same issue - Board Not Found. Tried creating lists from scratch and importing from Trello. Same issue. Verified that I am on the latest version - 1.07.0~2018-06-14. Please advise.

**Comment by xet7** [comment]
@ma4git 

Open issue about "Board not found" is at #1430 . It is not fixed yet. If you want to import for Trello etc, use Wekan Snap version.
