### ISSUE TITLE
Error: title is required

### ISSUE THREAD

**Issue by fbatschi** [wekan/wekan#1576]
## Issue

**Server Setup Information**:

* Deployment Method(snap/sandstorm/mongodb bundle):
Docker

* Http frontend (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
Nginx

* MongoDB Version:
3.2.19

**Problem description**:
I am running wekan as docker container. Had 0.63 and now updated to 0.80.
When starting the container, the following error occurs:

```
wekan-app  | Presence started serverId=kCvFwNiwpgTjAH7Dr
wekan-app  | > Starting add-checklist-items migration.
wekan-app  | /build/programs/server/node_modules/fibers/future.js:280
wekan-app  | 						throw(ex);
wekan-app  | 						^
wekan-app  | 
wekan-app  | Error: Title is required
wekan-app  |     at getErrorObject (packages/aldeed_collection2-core.js:480:15)
wekan-app  |     at ns.Collection.doValidate (packages/aldeed_collection2-core.js:462:13)
wekan-app  |     at ns.Collection.Mongo.Collection.(anonymous function) [as insert] (packages/aldeed_collection2-core.js:214:25)
wekan-app  |     at packages/matb33_collection-hooks.js:127:46
wekan-app  |     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
wekan-app  |     at Object.directOp (packages/matb33_collection-hooks.js:47:27)
wekan-app  |     at Object.self.direct.(anonymous function) [as insert] (packages/matb33_collection-hooks.js:126:30)
wekan-app  |     at _.sortBy.forEach (server/migrations.js:195:29)
wekan-app  |     at Array.forEach (<anonymous>)
wekan-app  |     at Checklists.find.forEach.checklist (server/migrations.js:194:39)
wekan-app  |     at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1053:16)
wekan-app  |     at Cursor.(anonymous function) [as forEach] (packages/mongo/mongo_driver.js:875:44)
wekan-app  |     at Object.Migrations.add [as migrationCallback] (server/migrations.js:192:21)
wekan-app  |     at packages/idmontie_migrations.js:238:17
wekan-app  |     at Function.time (/build/programs/server/profile.js:309:28)
wekan-app  |     at /build/programs/server/boot.js:423:13
```

Downgrading the container to 0.75 fixes it and wekan runs normally.
It seems as if an migration had not run here?

**Comment by pierreozoux** [comment]
@xet7 I'm experiencing the same, let me know if you need some debugging.

**Comment by fbatschi** [comment]
Is anyone running an instance beyond 0.75 without this problem?

**Comment by xet7** [comment]
I got this kind of error. I will look at it.

```
$ ./start-wekan.sh 
Presence started serverId=m7nxjh6qfd5YidRQn
> Starting board-background-color migration.
> Finishing board-background-color migration.
> Starting lowercase-board-permission migration.
> Finishing lowercase-board-permission migration.
> Starting change-attachments-type-for-non-images migration.
> Finishing change-attachments-type-for-non-images migration.
> Starting card-covers migration.
> Finishing card-covers migration.
> Starting use-css-class-for-boards-colors migration.
> Finishing use-css-class-for-boards-colors migration.
> Starting denormalize-star-number-per-board migration.
> Finishing denormalize-star-number-per-board migration.
> Starting add-member-isactive-field migration.
> Finishing add-member-isactive-field migration.
> Starting add-sort-checklists migration.
/home/USERNAME/repos/wekan/.build/bundle/programs/server/node_modules/fibers/future.js:280
						throw(ex);
						^

TypeError: checklist.items.forEach is not a function
    at Checklists.find.forEach (server/migrations.js:143:21)
    at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1053:16)
    at Cursor.(anonymous function) [as forEach] (packages/mongo/mongo_driver.js:875:44)
    at Object.Migrations.add [as migrationCallback] (server/migrations.js:135:21)
    at packages/idmontie_migrations.js:238:17
    at Function.time (/home/USERNAME/repos/wekan/.build/bundle/programs/server/profile.js:309:28)
    at /home/USERNAME/repos/wekan/.build/bundle/programs/server/boot.js:423:13
    at /home/USERNAME/repos/wekan/.build/bundle/programs/server/boot.js:464:5
    at Function.run (/home/USERNAME/repos/wekan/.build/bundle/programs/server/profile.js:510:12)
    at /home/USERNAME/repos/wekan/.build/bundle/programs/server/boot.js:462:11
```

**Comment by xet7** [comment]
@pierreozoux 

Yes, help is very welcome.

Previously checklists were in same "table". Now from there, checklist items are being migrated to another "table", this makes it easier to sort checklist items with drag-and-drop. Some column names could be wrong in migration.

Old checklists:
https://github.com/wekan/wekan/blob/v0.63/models/checklists.js

Old migrations:
https://github.com/wekan/wekan/blob/v0.63/server/migrations.js

New checklists:
https://github.com/wekan/wekan/blob/devel/models/checklists.js

New checklist items:
https://github.com/wekan/wekan/blob/devel/models/checklistItems.js

New migrations:
https://github.com/wekan/wekan/blob/devel/server/migrations.js

Build from source or in Docker instructions are in bottom of this page:
https://github.com/wekan/wekan/releases/tag/v0.83

Please submit pull request to Wekan devel branch! Thanks!

**Comment by xet7** [comment]
@andresmanelli 

Can you look at this? Upgrading Wekan does not work.

**Comment by pierreozoux** [comment]
@xet7 are you saying that it is fixed? And we should try the latest version to confirm it is fixed?

**Comment by xet7** [comment]
@pierreozoux 

This is not fixed. I'm trying to upgrade my own Wekan board, it does not work.

**Comment by pierreozoux** [comment]
Thanks a lot @xet7 :tada:

**Comment by fbatschi** [comment]
unfortunately does not fix it for me. the original error still persists when launching 0.85:

```
wekan-app  | Presence started serverId=Qfu6Ge8GrrAhCBs94
wekan-app  | > Starting add-checklist-items migration.
wekan-app  | /build/programs/server/node_modules/fibers/future.js:280
wekan-app  | 						throw(ex);
wekan-app  | 						^
wekan-app  | 
wekan-app  | Error: Title is required
wekan-app  |     at getErrorObject (packages/aldeed_collection2-core.js:480:15)
wekan-app  |     at ns.Collection.doValidate (packages/aldeed_collection2-core.js:462:13)
wekan-app  |     at ns.Collection.Mongo.Collection.(anonymous function) [as insert] (packages/aldeed_collection2-core.js:214:25)
wekan-app  |     at packages/matb33_collection-hooks.js:127:46
wekan-app  |     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
wekan-app  |     at Object.directOp (packages/matb33_collection-hooks.js:47:27)
wekan-app  |     at Object.self.direct.(anonymous function) [as insert] (packages/matb33_collection-hooks.js:126:30)
wekan-app  |     at _.sortBy.forEach (server/migrations.js:195:29)
wekan-app  |     at Array.forEach (<anonymous>)
wekan-app  |     at Checklists.find.forEach.checklist (server/migrations.js:194:39)
wekan-app  |     at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1053:16)
wekan-app  |     at Cursor.(anonymous function) [as forEach] (packages/mongo/mongo_driver.js:875:44)
wekan-app  |     at Object.Migrations.add [as migrationCallback] (server/migrations.js:192:21)
wekan-app  |     at packages/idmontie_migrations.js:238:17
wekan-app  |     at Function.time (/build/programs/server/profile.js:309:28)
wekan-app  |     at /build/programs/server/boot.js:423:13
wekan-app exited with code 1
```

**Comment by xet7** [comment]
Probably Title needs to be set as optional somehow.

**Comment by Daniel231** [comment]
Does the error fixed?

**Comment by pierreozoux** [comment]
Sorry to reply here after so long time, but I'm still experimenting that.
I'm still stuck at 0.74, and can't upgrade (I tried various versons, and also the v1.04)
I other wekan, no issue, it happened to me to just one instance.

Is there anything I can provide to help debug?
(I have the exact same error message)
Should we reopen?

**Comment by pierreozoux** [comment]
Just tried 1.07, and got the exact same issue:
```
app_1  | > Starting add-checklist-items migration.
app_1  | /build/programs/server/node_modules/fibers/future.js:280
app_1  | 						throw(ex);
app_1  | 						^
app_1  | 
app_1  | Error: Title is required
app_1  |     at getErrorObject (packages/aldeed_collection2-core.js:480:15)
app_1  |     at ns.Collection.doValidate (packages/aldeed_collection2-core.js:462:13)
app_1  |     at ns.Collection.Mongo.Collection.(anonymous function) [as insert] (packages/aldeed_collection2-core.js:214:25)
app_1  |     at packages/matb33_collection-hooks.js:127:46
app_1  |     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
app_1  |     at Object.directOp (packages/matb33_collection-hooks.js:47:27)
app_1  |     at Object.self.direct.(anonymous function) [as insert] (packages/matb33_collection-hooks.js:126:30)
app_1  |     at _.sortBy.forEach (server/migrations.js:195:29)
app_1  |     at Array.forEach (<anonymous>)
app_1  |     at Checklists.find.forEach.checklist (server/migrations.js:194:39)
app_1  |     at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1053:16)
app_1  |     at Cursor.(anonymous function) [as forEach] (packages/mongo/mongo_driver.js:875:44)
app_1  |     at Object.Migrations.add [as migrationCallback] (server/migrations.js:192:21)
app_1  |     at packages/idmontie_migrations.js:238:17
app_1  |     at Function.time (/build/programs/server/profile.js:309:28)
app_1  |     at /build/programs/server/boot.js:423:13
```

Should I try to run the migration manually? How could I start a meteor shell from docker?
(I guess I'll  have to compile a manual docker image for that, but maybe you have something quicker)

**Comment by pierreozoux** [comment]
@xet7 the fix you applied, was for `add-sort-checklists` , but here, the failing migration is on `add-checklist-items`.

**Comment by xet7** [comment]
@pierreozoux 

After this Docker image is built in a moment, please test that it fixes this issue:
```
image: quay.io/wekan/wekan
```
