### ISSUE TITLE
meteor bundle tar.gz are missing

### ISSUE THREAD

**Issue by Madko** [wekan/wekan#1869]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?: can't do
* Wekan version: 1.20
* If this is about old version of Wekan, what upgrade problem you have?: can't find newer tar.gz 
* Operating System: Linux CentOS 7
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): meteor bundle
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first): nginx
* Node Version: 8.11.2
* MongoDB Version: 2.6.12

**Problem description**:
https://github.com/wekan/wekan/wiki/Meteor-bundle points to download URL where we used to find meteor bundle. Seems last is 1.20. Newer version are only available as .spk (sandstorm?)

Please, can you provide newer tar.gz for wekan meteor bundle ?

Best regards,
Edouard

**Comment by xet7** [comment]
Done, newest tar.gz for Wekan v1.41 is available:
https://releases.wekan.team

**Comment by Madko** [comment]
@xet7 thanks !

**Comment by Madko** [comment]
Seems the problem is back. Can't find 1.53 tarball.

Best regards,
Edouard

**Comment by xet7** [comment]
I had some time, so I added 1.58 tarball.

Please add comment again when you need new tarball, sometimes I forget or don't have enough time.
