### ISSUE TITLE
Wekan export internal server error

### ISSUE THREAD

**Issue by ashgoodman** [wekan/wekan#2093]
When I try to export a board I get an internal server error and a file with a size of 0 bytes

Tested in Firefox and Chrome

Running on an Ubuntu 18.04 Server

**Comment by fsainovich** [comment]
Same here

**Comment by xet7** [comment]
What Wekan platform (Snap/Docker/Sandstorm) ? For me, export works on Wekan v2.90 Snap.
Please try doing this:
```
sudo snap set wekan with-api='true'
```

**Comment by Teutone** [comment]
Just happened here, too. This is on wekan `docker`, self-built the `Dockerfile`, docker-compose setup. Imported database from backup using `mongorestore`, other than that all standard. `Wekan Version v3.11.0`

Logs show:

```
2019-08-08T22:12:03.781366794Z wekan-app 8495 MongoError: file with id 5d4c9e33fb96e2212f8dbbbe not opened for writing
2019-08-08T22:12:03.781405722Z wekan-app 8495     at Function.MongoError.create (/build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11)
2019-08-08T22:12:03.781417435Z wekan-app 8495     at /build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/gridfs/grid_store.js:979:33
2019-08-08T22:12:03.781427592Z wekan-app 8495     at handleCallback (/build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/utils.js:96:12)
2019-08-08T22:12:03.781435629Z wekan-app 8495     at /build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/collection.js:1401:5
2019-08-08T22:12:03.781444945Z wekan-app 8495     at handleCallback (/build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/utils.js:96:12)
2019-08-08T22:12:03.781452132Z wekan-app 8495     at /build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/cursor.js:675:5
2019-08-08T22:12:03.781459019Z wekan-app 8495     at handleCallback (/build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:172:5)
2019-08-08T22:12:03.781465496Z wekan-app 8495     at setCursorNotified (/build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:517:3)
2019-08-08T22:12:03.781473132Z wekan-app 8495     at /build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:590:16
2019-08-08T22:12:03.781482717Z wekan-app 8495     at queryCallback (/build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:233:18)
2019-08-08T22:12:03.781494114Z wekan-app 8495     at /build/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:436:18
2019-08-08T22:12:03.781501236Z wekan-app 8495     at _combinedTickCallback (internal/process/next_tick.js:132:7)
2019-08-08T22:12:03.781508675Z wekan-app 8495     at process._tickDomainCallback (internal/process/next_tick.js:219:9)
```

**Comment by xet7** [comment]
@Teutone 

What MongoDB version you have?

**Comment by Teutone** [comment]
```
MongoDB shell version v4.0.11
```

**Comment by xet7** [comment]
https://github.com/wekan/wekan/issues/2533#issuecomment-517999731

**Comment by xet7** [comment]
@Teutone 

Please add your docker commands and settings you used, without your own domains and credentials included.

**Comment by xet7** [comment]
@Teutone 

What Docker image are you using?

**Comment by xet7** [comment]
I'm just thinking, if you use latest tag, without version tag, I don't know would this https://github.com/wekan/wekan/pull/2603 by @whowillcare have any effects on this.

**Comment by xet7** [comment]
Did you use newest docker-compose.yml from https://github.com/wekan/wekan ?

**Comment by Teutone** [comment]
Built the docker image myself using the Dockerfile from master 9ed0c3029f7a61a9e5cc31d52156055e08e53f9a

Yes, used docker-compose.yml from master

**Comment by xet7** [comment]
Do you have old data at /data/db ? https://github.com/wekan/wekan/issues/2585#issuecomment-518689831

**Comment by Teutone** [comment]
No, it's fresh `mongo:4.0` docker image without data. 

- first stopped wekan-app
- then imported with `mongorestore`
- then started wekan-app

**Comment by xet7** [comment]
I did test building Docker image. I did uncomment these lines https://github.com/wekan/wekan/blob/master/docker-compose.yml#L132-L142 and then did:
```
docker-compose up -d --build
```
And Wekan is available at port 80 just fine. I don't know how you did build your Docker image.

**Comment by Teutone** [comment]
And does board export work for you?

**Comment by xet7** [comment]
You need to import with:
``` 
mongorestore --drop --noIndexRestore
```

**Comment by xet7** [comment]
Yes, export board works for me, on that container I just built above.

**Comment by Teutone** [comment]
Yes I used that command from https://github.com/wekan/wekan/wiki/Export-Docker-Mongo-Data
Sorry, should have been more detailed

**Comment by Teutone** [comment]
Just tested with another board - and it seems it's just one board that makes problems. I can export other boards just fine. 
If I remember correctly I was not admin from the start for that board where export fails. Maybe that's causing some problem?

**Comment by xet7** [comment]
Hmm, I have not tested is export enabled for normal users.

**Comment by Teutone** [comment]
I could not export a board where I was not admin. So I kindly asked the creator of the board to make me admin. Now export doesn't work with just that board - maybe it's a permission problem.

**Comment by xet7** [comment]
With only one board? You can try to build Wekan container again, I just fixed one permission problem:
https://github.com/wekan/wekan/commit/9f6d615ee5bbdb7552e6bdcae75a76a7f74fef7a

**Comment by xet7** [comment]
Correction: other Wekan contributor fixed it.

**Comment by Teutone** [comment]
Just tried it, but didn't fix the buggy board. Can't export only a few boards, trying to find out why

**Comment by tesfithagos** [comment]
I have the same problem, is there a solution now?
I use Apache2 as a web server, i can see these messages in the logs:

[proxy_http:error]  
(20014)Internal error (specific information not available):
AH01102: error reading status line from remote server wekan.*****.**:3001
AH00898: Error reading from remote server returned by /api/boards/***********/export

On some boards it works and on some it does not work.

**Comment by xet7** [comment]
@tesfithagos 

Are you BoardAdmin on those boards you are trying to export?

**Comment by tesfithagos** [comment]
yes

**Comment by lime918** [comment]
present on one of my boards running wekan v3.29, ubuntu 16.10, mongo 3.2.22.

**Comment by xarinatan** [comment]
I presume I'm also getting this issue inside Sandstorm, Version 2.97.0~2019-07-01, I don't see any errors pop up though, neither in the Networking tab of the webbrowser console, nor in the sandstorm debug log.. but I'm getting a 0 bytes file every time I try export any of the boards from an older grain that's been around for a while, in fresh grains it works fine but in that specific grain none of the boards can be exported, even fresh boards.

**Comment by lime918** [comment]
poked around the log a bit. I have the same error as teutat3s:

MongoError: file with id 5cae8de230a374304a5f7152 not opened for writing

**Comment by xet7** [comment]
Moved to here from https://community.vanila.io/home?t=28ccfe48-0f4c-435e-a822-d8d22dafa94c

@whowillcare 

Currently exporting board does not work, when there is attachments on boards like images. I don't know are these related to your changes to save attachments to disk instead of MongoDB. There are some errors related to cfs-upload. Do you have time to look at this?

![export-bug-2](https://user-images.githubusercontent.com/15545/66277435-4d905d80-e8a7-11e9-84a8-f73480dff94c.png)

![export-bug-1](https://user-images.githubusercontent.com/15545/66277441-58e38900-e8a7-11e9-93c2-b0b987980a11.png)

![export-bug-3](https://user-images.githubusercontent.com/15545/66277444-626cf100-e8a7-11e9-8694-df1f07b46681.png)

**Comment by whowillcare** [comment]
Will talk a look when I have time
