### ISSUE TITLE
[Bug] Subtasks can not be set at first time and the Subtask-Board create mutliple swimlanes

### ISSUE THREAD

**Issue by sfahrenholz** [wekan/wekan#2256]
## Issue

**Server Setup Information**:

* Did you test in newest Wekan?: yes (2.43 and 2.45) on Ubuntu snap with current dependencies

**Problem description**:
(1) the first creating i cant see the subtask
(2) to "jump" into the subtask-board is only to link one card. a entry in the menu are better
(3) i missing a description for the subtask in the wiki (how it works and more)

![ribcu-9cuy4](https://user-images.githubusercontent.com/6977657/54058822-4dd45780-41f7-11e9-8291-36c674ac56b7.gif)

edit:
i forgot to descripted:
For every Subtask a new Swimlane with the Queue is created. A picture say more than words..
![image](https://user-images.githubusercontent.com/6977657/54068990-d8967000-4252-11e9-959f-2d94a978b036.png)

mention from and create new issue:
https://github.com/wekan/wekan/issues/2241#issuecomment-471093550

**Comment by xet7** [comment]
@sfahrenholz 

Please test Wekan v2.46 does this still happen.

**Comment by sfahrenholz** [comment]
@xet7 
The multi swimlane are fixed. but (1) the first creation of subtasks (gif) are still there and (2) every Subtasks gets an own list

![image](https://user-images.githubusercontent.com/6977657/54339315-c3478a00-4634-11e9-87db-e587dbb51c33.png)

**Comment by sfahrenholz** [comment]
I testing the Version 2.51

When i creating a new Board with three Lists. On List 1 i add an card with subtask 1, so i can "View it" in the subtaskboard and there are 3 "Queue Lists". The first Subtask for List 1 is added to Queue One but the second card is a add to Queue two.

![ezgif-4-da47f9740094](https://user-images.githubusercontent.com/6977657/54735539-0eb6e680-4ba7-11e9-95eb-22df5493161c.gif)

Subtask-board
![image](https://user-images.githubusercontent.com/6977657/54735549-23937a00-4ba7-11e9-88fc-a5c56e3efce3.png)

**Comment by xet7** [comment]
## Workaround to get Subtasks working

https://github.com/wekan/wekan/wiki/Subtasks

**Comment by rasos** [comment]
Subtasks did not work on all boards here on a sandstorm deplyoment  with Wekan 2.47.0~2019-03-14. I can confirm that the workaround adds subtasks capability on a project which was launched in March 2019 when adding a ^board^ and asigning it as subtasks board. I assume that this should be done automagically in a more recent Wekan version, which is not available for Sandstorm yet.

**Comment by xet7** [comment]
@rasos 

Links to current official and experimental Wekan versios are Sandstorm wiki page:
https://github.com/wekan/wekan/wiki/Sandstorm

Current [official version](https://apps.sandstorm.io/app/m86q05rdvj14yvn78ghaxynqz7u2svw6rnttptxx49g1785cdv1h) is Wekan v2.61.

Current [experimental version](https://apps.sandstorm.io/app/m86q05rdvj14yvn78ghaxynqz7u2svw6rnttptxx49g1785cdv1h?experimental=true) is Wekan v2.86, also available as .spk file at https://releases.wekan.team .

I do know @ocdtrekkie is very busy, I hope he can sometime test experimental Wekan version, can it be accepted as official Sandstorm version.

If you have your own server with your own Sandstorm install, and very good tested backups of full Sandstorm and all grains separately, you can try installing experimental Wekan version to your server, updating all grains. But you should not try experimental version on Oasis. After upgrading Wekan and grains, it's not possible to downgrade, it requires removing Wekan and Wekan grains and installing previous Wekan version and Wekan grains from backup.

**Comment by xet7** [comment]
Yes I do know @ocdtrekkie is waiting for fix for [this bug](https://github.com/sandstorm-io/sandstorm/issues/3132#issuecomment-485948463), I should fix it to motivate @ocdtrekkie to update Wekan on Sandstorm. Current workaroud is to click All Boards link.

**Comment by jtktam** [comment]
i can confirm multiple swimlane issue still exist on the docker image

each subtask i added to the parent task adds a new swimlane in the subtask board

**Comment by Cawet** [comment]
Hi !
Same problem here. 
It happens some times in a week, and that's a must have for us and it's a pain to clean everything when that bug occurs. 
Anyway, here is how exactly reproduce this bug : 

**Initial state**
- We have a "child" and a "parent" board. 
- The child board is set as the destination in the parent's subtask parameters.
- The column you want subtasks to fall in, is setted in the child's subtask parameters.

**A : It work as expected if   :** 
- You go to the parent board, by using the wekan UI (for ex. the top menu bar or the main "all board" page
- You go to the parent board, using the navigation pannel on the very top bar of the dashboard (where all your starring boards are pinned)
- You create some subtask
-> As a result, the subtask goes in the right column of the child board and no extra swimlanes / columns are created

**B: It creates some extra swimlanes and columns when :** 
- Yo land on the parent board directly, because you bookmark it, you open it on a new tab, or you simply reload (f5) the page
- You start creating subtasks
-> Subtasks are going right into a new auto created swimlane / column in the child board. 
-> Now, even if you navigate as in A, it always create new swimlanes (or sometime, it fall into nothing, where you can't find the task anywhere). 
-> If you set again the right destination column in the child board, and you navigate as in A, it will work again properly.

I hope this might helps, I can do extra test if needed.

**Comment by badguybluebane** [comment]
> Hi !
> Same problem here.
> It happens some times in a week, and that's a must have for us and it's a pain to clean everything when that bug occurs.
> Anyway, here is how exactly reproduce this bug :
> 
> **Initial state**
> 
>     * We have a "child" and a "parent" board.
> 
>     * The child board is set as the destination in the parent's subtask parameters.
> 
>     * The column you want subtasks to fall in, is setted in the child's subtask parameters.
> 
> 
> **A : It work as expected if :**
> 
>     * You go to the parent board, by using the wekan UI (for ex. the top menu bar or the main "all board" page
> 
>     * You go to the parent board, using the navigation pannel on the very top bar of the dashboard (where all your starring boards are pinned)
> 
>     * You create some subtask
>       -> As a result, the subtask goes in the right column of the child board and no extra swimlanes / columns are created
> 
> 
> **B: It creates some extra swimlanes and columns when :**
> 
>     * Yo land on the parent board directly, because you bookmark it, you open it on a new tab, or you simply reload (f5) the page
> 
>     * You start creating subtasks
>       -> Subtasks are going right into a new auto created swimlane / column in the child board.
>       -> Now, even if you navigate as in A, it always create new swimlanes (or sometime, it fall into nothing, where you can't find the task anywhere).
>       -> If you set again the right destination column in the child board, and you navigate as in A, it will work again properly.
> 
> 
> I hope this might helps, I can do extra test if needed.

Same problem here

**Comment by xet7** [comment]
Fixed in commit 4b27313c7 ( https://github.com/wekan/wekan/commit/4b27313c7 ), in the upcoming WeKan release. Subtask creation is now server-authoritative (new addSubtaskCard Meteor method) and the client-side auto-creation of the default subtasks board/list is guarded to the server, so the client can no longer create duplicate subtasks boards/swimlanes/columns and multiple subtasks can be created reliably. Reopen if it still reproduces on the latest version.
