### ISSUE TITLE
Bug: Some IFTTT Rule is preventing adding User to a card since 2.51

### ISSUE THREAD

**Issue by Montiemedia** [wekan/wekan#2278]
## Issue

After Update with snap from 2.40 to 2.51, you can´t add a User to a card. In the log on the right side, you see the assignment. But in the card, the User pulls out.

On a new board, that is createad after update, this function does work.

WEKAN Version: 2.51.0
Node: 8.15.1
OS: RHEL 7
Deploy: snap
Http frontend: nginx

![card](https://user-images.githubusercontent.com/10979237/54762252-033ddc80-4bf4-11e9-89d1-6aeaf0ad6f5b.gif)

**Comment by sfahrenholz** [comment]
Hello @Montiemedia 
thank you for reporting. can you give us the logfile? on snap `snap logs wekan`

on my testsystem i can add the member without any problems

**Comment by Montiemedia** [comment]
I can´t find any logs :(

**Comment by sfahrenholz** [comment]
has the card moved in the last time? Maybe it is the same issue as https://github.com/wekan/wekan/issues/2238#issuecomment-470972136

**Comment by Montiemedia** [comment]
In a new Board, created after update, everything works fine. 

I´ve restored the system from our backup. After restore, I will try a new update and give more feedback.

**Comment by Montiemedia** [comment]
In new cards in a old board, is the same failure. 
Then swimlane ID is empty.

**Comment by Montiemedia** [comment]
I found the problem.

It seems to be the same bug, as in this report by me: https://github.com/wekan/wekan/issues/1899

I´ve deleted all rules, and now I can add user to cards.

**Comment by xet7** [comment]
@Montiemedia 

What IFTTT Rule it was, that prevented adding user?

**Comment by Montiemedia** [comment]
I´ve created a rule, that a new card, without adding a user, is set to a defined Lane.

**Comment by sfahrenholz** [comment]
Rule:
- When a card is added to List list in swimlane * by * => add member user
- When a card is added to List * in swimlane * by * => add member user

![image](https://user-images.githubusercontent.com/6977657/54812232-edc7c180-4c8a-11e9-8fac-b28a2a41b32e.png)

**Comment by sfahrenholz** [comment]
In 2.52 still exists

![image](https://user-images.githubusercontent.com/6977657/54825497-072e3500-4cae-11e9-95d6-d28364987605.png)

**Comment by sfahrenholz** [comment]
seem like fixed in 2.59

Rule: 
![image](https://user-images.githubusercontent.com/6977657/55669413-3d0b1600-5877-11e9-8373-44052fbf8aa1.png)

**Comment by Montiemedia** [comment]
No, it´s not fixed. :-(
I´ve tried the rules again, and the bug ist still there in v2.60 2019-04-08

**Comment by sfahrenholz** [comment]
@xet7 can conform, the issue is back

![image](https://user-images.githubusercontent.com/6977657/56283978-7b27f580-6113-11e9-9862-b49c4e5f90fd.png)

**Comment by sfahrenholz** [comment]
@Montiemedia 
please check your rules. i have testing a little bit. if a rule match the conditions too, other rules where not evaluated.
in my case:
(1) Add user {user1} to all cards at list A
(2) Add user {user2} to all cards at list A

The first rule can not be add successful, because user 1 ist not existing
