### ISSUE TITLE
Unable to access API in Wekan Docker version

### ISSUE THREAD

**Issue by ChristianGroeber** [wekan/wekan#3365]
## Issue

I always get a 401:Unauthorized message when I try to access the API after successfully logging in.

### Login:

```
curl -H 'Accept: application/json' \
       -H 'Content-Type: application/x-www-form-urlencoded' \
       -d 'username=christian'  \
       -d 'password=[my-password]' \ 
       [host]/users/login
```

**Response:**
```
{
    "id": "C9LYk9SCd5Qph9sCN",
    "token": "[token]",
    "tokenExpires":"2021-02-21T09:58:50.108Z"
}
```

### Test Request:
```
curl -H 'Authorization: [token]' \
      -H 'Accept: application/json' \
      -X GET [domain]/api/boards
```
**Response:**
```
{
    "isClientSafe": true,
    "error": "Unauthorized",
    "reason": "Unauthorized",
    "message": "Unauthorized [Unauthorized]",
    "errorType": "Meteor.Error",
    "statusCode":401
}
```

### Server Setup Information:

* Note: Please anonymize info, and do not add to this public issue any of your Wekan board URLs, passwords, API tokens etc, do you understand?: Yes
* Did you test in newest Wekan?: Yes
* Wekan version: 4.55.0
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): Docker
* Node Version: 12.19.1
* MongoDB Version: 4.4.2

**Comment by xet7** [comment]
It seems API does not work in Docker version of Wekan. I don't know yet why.

API works in Snap version.

**Comment by xet7** [comment]
I did test this with [wekan.py](https://github.com/wekan/wekan/wiki/New-card-with-Python3-and-REST-API#wekanpy-creating-new-card-with-python3-and-rest-api) .

Wekan Docker version gives error:
```
$ ./wekan.py
=== Wekan API Python CLI: Shows IDs for addcard ===
AUTHORID is USERID that writes card.
Syntax:
  python3 wekan.py users              # All users
  python3 wekan.py boards USERID      # Boards of USERID
  python3 wekan.py board BOARDID      # Info of BOARDID
  python3 wekan.py swimlanes BOARDID  # Swimlanes of BOARDID
  python3 wekan.py lists BOARDID      # Lists of BOARDID
  python3 wekan.py createlist BOARDID LISTTITLE # Create list
  python3 wekan.py addcard AUTHORID BOARDID SWIMLANEID LISTID CARDTITLE CARDDESCRIPTION
Traceback (most recent call last):
  File "./wekan.py", line 114, in <module>
    apikey = d['token']
KeyError: 'token'
```
Wekan Snap version does not show any errors, and commands like this works:
```
$ ./wekan.py users
```

**Comment by xet7** [comment]
Also I presume Source Bundle version of Wekan should also have working API:
https://github.com/wekan/wekan/wiki/Raspberry-Pi

I don't know has there been some changes in Docker software that would cause Wekan API not working in Docker?
In docker-compose.yml from https://github.com/wekan/wekan there is setting `WITH_API=true` that should make API enabled.

**Comment by xet7** [comment]
If there is need for containerization, but Docker does not work, another option is to use Source Bundle install on LXC:
https://github.com/wekan/wekan-snap/wiki/Many-Snaps-on-LXC

**Comment by ChristianGroeber** [comment]
@xet7 Okay, is that something you are working on fixing? Otherwise I could try and get it working (though I can't promise much)

**Comment by xet7** [comment]
@ChristianGroeber 

You, or anyone else can look at this. I don't know why this happens, I'm currently coding other big features.

**Comment by xet7** [comment]
@ChristianGroeber 

I think this is because of wrong username.

a) If Wekan has OAuth2, LDAP or other 3rd party login, username is usually email address.
b) If someone has registered to Wekan using Wekan password login, username is username.

I fixed this to my code https://github.com/wekan/wekan/wiki/New-card-with-Python3-and-REST-API

**Comment by ChristianGroeber** [comment]
@xet7 But if I was using the wrong username, then why can I get an Authentication token? This issue isn't fixed yet. The problem really seems to be when accessing the API through Docker. The Website can be accessed normally though.

**Comment by MonkeyNinja** [comment]
@ChristianGroeber your authorization header is missing the Bearer keyword

--header "authorization: Bearer 60WJ7uT7iDL9nqsXtSp4nV-W-rqqOBkn4I-pm06GNRf"

**Comment by ChristianGroeber** [comment]
@MonkeyNinja Oooh my goodness, thank you so much! Only half a year later and we fixed the problem of the buggy API

@xet7 Thank you very much, you can close this Issue now

**Comment by Pocok256** [comment]
> @ChristianGroeber your authorization header is missing the Bearer keyword
> 
> --header "authorization: Bearer 60WJ7uT7iDL9nqsXtSp4nV-W-rqqOBkn4I-pm06GNRf"
> 
> This looks like a bit of an oversight in the API documentation too, /users/login returns a token - the rest of the documentation refers to an an 'API_KEY'

Thx bro save my day :D
