### ISSUE TITLE
Cannot find module /build/main.js after update to latest

### ISSUE THREAD

**Issue by gpalyu** [wekan/wekan#3441]
I updated to the latest package in docker, and when I re-started I get the following error. Can anyone please help me get this back up and running? I did not expect this to break on a regular update. :(

Error: Cannot find module '/build/main.js'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
at Function.Module._load (internal/modules/cjs/loader.js:667:27)
at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
at internal/main/run_main_module.js:17:47 {
code: 'MODULE_NOT_FOUND',
requireStack: []

**Server Setup Information**:

* Wekan version: latest
* If this is about old version of Wekan, what upgrade problem you have?:
* Operating System: Synology OS
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): Docker
* Http frontend if any (Caddy, Nginx, Apache, see config examples from Wekan GitHub wiki first):
* Node Version:
* MongoDB Version: latest

**Comment by xet7** [comment]
Oops :D Just a moment, I'll revert some Dockerfile changes :D

**Comment by gpalyu** [comment]
Oh thank god. I thought I was really screwed, I have been trying to fix this for the last hour. Thank you @xet7

**Comment by xet7** [comment]
@gpalyu 

It's much easier to fix something when somebody adds new issue or comment about that something is broken :D There is new major and minor features and fixes being added to Wekan daily, so it's kind of rocket surgery.

**Comment by gpalyu** [comment]
I am back up and running, thank you again for fixing this so quickly.

**Comment by xet7** [comment]
@gpalyu 

Please try downloading newest Docker container, it has finished building now.

**Comment by GavinLilly** [comment]
@gpalyu Do you know exactly what Docker version you were running when it failed?

The part that doesn't make any sense to me is that the new Dockerfile I merged in doesn't execute `/build/main.js`, it executes `/bundle/main.js` so I wonder if there's a caching issue in Docker

**Comment by gpalyu** [comment]
@GavinLilly I believe it was 4.80, I think this is the case because I tried downloading the previous version which was 4.79 and still have that in my docker. Xet7 rebuilt the files and I downloaded them a little later and the issue was resolved with no further work on my end.

**Comment by GavinLilly** [comment]
You can see in the manifest for the Docker image on [quay.io](https://quay.io/repository/wekan/wekan/manifest/sha256:7b9c5c9dbfea9fdb9d368cfd1ae915604c3fe212d00f9a6327e240f0d7ff99cc) that it's executing `/bundle/main.js`.

I'm going to pull down the v4.80 image tonight and check because I'm not convinced it's the source of the problem
