### ISSUE TITLE
Bug: Wekan - Synology 

### ISSUE THREAD

**Issue by marek94901** [wekan/wekan#3874]
Hi,

wekan doesn't work for us today. I don't know what caused the defect, but I noticed the download of a new image via watchtower. We use docker on our synology nas. 

wekan: v5.35
mongo db: 4.4.6
synology docker app: 20.10.3.-0552

Here is a list of logs:

ReferenceError: describe is not defined
    at module (server/lib/utils.tests.js:6:1)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at require (packages/modules-runtime.js:258:21)
    at /build/programs/server/app/app.js:27729:1
    at /build/programs/server/boot.js:401:38
    at Array.forEach (<anonymous>)
    at /build/programs/server/boot.js:226:21
    at /build/programs/server/boot.js:464:7
    at Function.run (/build/programs/server/profile.js:280:14)
    at /build/programs/server/boot.js:463:13

Thanks.

**Comment by xet7** [comment]
@marek94901 

1) Stop wekan-app and remove it:
```
docker stop wekan-app
docker rm wekan-app
```
2a) Try with this image:
```
image: quay.io/wekan/wekan:v5.25
```
2b) or this image:
```
image: wekanteam/wekan:v5.35
```
If you use docker commands, use [something like this](https://github.com/wekan/wekan/wiki/Docker#example-for-latest-wekan-port-2000-to-docker-wekan-internal-port-8080):
```
docker run -d --restart=always --name wekan --link "wekan-db:db" -e "WITH_API=true" -e "MONGO_URL=mongodb://wekan-db:27017/wekan" -e "ROOT_URL=http://192.168.1.200:2000" -p 2000:8080 quay.io/wekan/wekan:v5.35
```
If you use instead use docker-compose, after changing docker-compose.yml do:
```
docker-compose up -d
```

**Comment by Major2828** [comment]
Had same error, changing image to image: quay.io/wekan/wekan helped me.
In the same time I also updated the docker.compose.yml (update mongoDB to 4.4 and update the start command for mongoDB) but I think it has nothing to do with mongoDB

**Comment by xet7** [comment]
@Major2828 

I don't recommend running that latest tag like in your example, because there are In Progress incomplete features like Shared Templates. I recommend running release tags like v5.35 like above in my example.

**Comment by Major2828** [comment]
@xet7 thank you for your response, i thought the latest tag would update only if a release happend? 
So actual latest would  be 5.35 or do i missanderstand something?

**Comment by xet7** [comment]
@Major2828 

No. Latest is newest git commit at master branch, and it can sometimes be broken, like unstable/devel. Wekan has only one branch, master. It builds every time there is new commit. Commits are here:
https://github.com/wekan/wekan/commits/master

Releases are when some specific release has numbered release tag, like v5.35. When release tag is added, then new Snap/Sandstorm/Bundle etc versions are built.

**Comment by Major2828** [comment]
@xet7 oh that is very interesting thank you very much, i will change it :)

**Comment by marek94901** [comment]
Hi, thank you very much for the advice. I was desperate in the morning, so I tried several methods and the last thing I could think of was to use the old image in version 5.35. This version works.

**Comment by gpalyu** [comment]
Can someone who has applied the fix tell me if it's possible to change the tag from latest to release in the Synology UI? I don't see that tag listed when I download a new image, but I can download version 5.35 specifically. I don't think there's a great way to change versions if I do 5.35 without updating things manually to a new version?

**Comment by xet7** [comment]
@gpalyu 

I don't know how you add or remove docker images in Synology UI, I don't have Synology.

With Docker, it's done this way: https://github.com/wekan/wekan/issues/3874#issuecomment-867526249

You see newest Wekan version from https://wekan.github.io/ above Download button, currently newest and greatest is Wekan v5.36, it includes all recent fixes.

I would think you remove previous wekan-app container and download newest with tag v5.36

**Comment by xet7** [comment]
You should keep your existing wekan-db (mongodb) container, and also have [daily backups](https://github.com/wekan/wekan/wiki/Backup)

**Comment by gpalyu** [comment]
Thank you @xet7 I figured out how to do this so I can run on a stable version all the time now.

**Comment by eriky** [comment]
Most, if not all, open-source projects point the latest tag to the latest release. I've never seen this being used in this way. I feel it would be better to conform to that de-facto standard instead of needing to warn people about this. This is probably going to be an issue for many users to come if left unchanged.

**Comment by xet7** [comment]
@eriky 

Latest tags do point to latest releases.

**Comment by modem7** [comment]
> Most, if not all, open-source projects point the latest tag to the latest release. I've never seen this being used in this way. I feel it would be better to conform to that de-facto standard instead of needing to warn people about this. This is probably going to be an issue for many users to come if left unchanged.

To echo @eriky, typically in open source projects that I've come across, latest is the latest stable release.

They then have tags for development/nightly etc where those releases are published to via the CI/CD system.

**Comment by xet7** [comment]
@modem7 

I already fixed that at 2021-11-12. When releasing, I push to release tags and latest tags:
- https://github.com/wekan/wekan/blob/master/releases/docker-push-gantt.sh
- https://github.com/wekan/wekan/blob/master/releases/docker-push-wekan.sh

**Comment by gohrner** [comment]
> @modem7
> I already fixed that at 2021-11-12. When releasing, I push to release tags and latest tags:

Maybe the [README.md](https://github.com/wekan/wekan/blob/master/README.md) should be adjusted then?

It still reads:

> Docker: Please only use Docker release tags
> Note: With Docker, please don't use latest tag. Only use release tags. See https://github.com/wekan/wekan/issues/3874

As I understood the your comment here, the `latest` tag should now be `safe`.

**Comment by C0rn3j** [comment]
@xet7 While you did fix the above in README.md, it's still hanging around in https://hub.docker.com/r/wekanteam/wekan

![image](https://github.com/wekan/wekan/assets/1641362/fbe9ff52-6bb6-43ba-a583-aac3ec27554b)

**Comment by xet7** [comment]
@C0rn3j 

I updated Docker Hub readme.
