### ISSUE TITLE
Bug: Attachments cannot be opened (.eml)

### ISSUE THREAD

**Issue by Meeques** [wekan/wekan#5052]
Server Setup Information
* Did you test in newest Wekan?: 7.03.0
* Operating System:
* Deployment Method Snap
* Http frontend if any Apache
* Node.js Version: 14.21.4
* MongoDB Version: 6.0.8

### Problem description
A colleague copied their board and made the copy avaiable to other colleagues with the respective permissions. Until ~19.07.23 they could work with that board without any problems. Then we got a ticket from them that they can't open .eml attachments anymore. They tried opening in browser and even downloading and opening in thunderbird. Both ways, they only get a blank page. 

Maybe there is something wrong with the systems permission management since an update?

Kind regards!

**Comment by Meeques** [comment]
I'm now pretending to be her by User takeover. Preview shows nothing, download can't be finished because of a missing authentication. This even happens with eml data she herself uploaded. 
Does the server maybe not hand over the correct permission?

**Comment by Meeques** [comment]
Attachment-icons are not shown on minicard, but in boardsettings, it is set to be shown on minicard. Just something I noticed just now.

**Comment by xet7** [comment]
@Meeques 

With User takeover / Impersonate user, maybe not everything yet works similar like actual logged in user. Other option is to change that user password at Admin Panel / People / People, and login as that user, if everyone is using password login.

If your WeKan uses LDAP, OAuth2 or similar login, then passwords are at that LDAP (or other auth) server admin, not in WeKan.

**Comment by xet7** [comment]
@Meeques 

> I can download and then open .eml data succesfully in firefox, but not in chrome.

That could be bug in Chrome.

**Comment by xet7** [comment]
It is not first time when in new version of Chrome, something that did previously did work, does not work anymore. 

Like Chrome broke this before #1404

**Comment by xet7** [comment]
Also something attachment related is broken in Safari #5042

**Comment by Meeques** [comment]
@xet7 not every file works in Firefox.. so not just a chrome problem. Thanks for the quick reply. We are not yet sure about the pattern. I will contact the affected person and try it with her account. I will test further options now and will give you an update asap. I just wanted you to take a quick look, in case this is something you know an ad hoc solution

**Comment by xet7** [comment]
@Meeques 

Originally, viewing attacments as big size when clicking them, did only work for bitmap images like PNG/JPG. Viewing PDF is very new feature.

Feature viewing .eml has been paid at #2936 , but AFAIK I have not developed it yet. Firefox itself could have feature for viewing .eml . When sometime I have time to develop that, from .eml WeKan will be able to extract content as text and attachments, and view it properly.

Viewing .SVG files could maybe work sometime, there probably was some fixes for that.

Viewing sound and video files works I think.

There is not yet support for viewing Office documents.

**Comment by Meeques** [comment]
The problem occurs when downloading. Viewing was and is not possible, but that is known and accepted.

**Comment by mfilser** [comment]
@xet7
I think it's completly different.

Maybe it's related to the previously PR #4995  ?

**Comment by xet7** [comment]
@VidVidex 

Do you know how to fix this? Cand you send PR ?

**Comment by VidVidex** [comment]
I'll take a look

**Comment by VidVidex** [comment]
I am not sure what the issue is. As far I can tell downloading eml files works as expected.
Maybe there is an issue with permissions.

What I did fix (#5058) is prevent the preview from opening if that file type is not supported (such as eml files).

**Comment by xet7** [comment]
Fixed at https://github.com/wekan/wekan/pull/5058 . Thanks to @VidVidex !

**Comment by Meridiana** [comment]
Our problem is not fixed, the viewer is not the problem as Meeques decribed earlier.
The download fails for some attachments, e.g.:

https://.../wekan/cdn/storage/attachments/5479a0fd5b6b8f12a88f196c/original/5479a0fd5b6b8f12a88f196c.eml?download=true

-> Status 401 Unauthorized

**Comment by Meeques** [comment]
Can you give me regular updates on this if you have them?

**Comment by Meridiana** [comment]
Nope - error 401 Permission denied remains.
Its Wekan 7.08.0 right now.

**Comment by JannetGen** [comment]
I’ve run into similar issues with .eml files showing up blank. As a quick workaround, you could try opening the file with OpenPST — it supports .eml directly in the browser and doesn’t require Outlook- [https://openpst.com/](https://openpst.com/).
Might be useful while the attachment handling in WeKan is being figured out.
